#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

VenueApp::Application.load_tasks

# Custom precompile
desc "Precompile assets using the 'Production' environment (usually before deploying)"
task :precompile do
  sh "rm -rf ./tmp/cache/assets/production/*"
  sh "rm -rf ./public/assets/*"
  sh "RAILS_ENV=production rake assets:clean"
  sh "RAILS_ENV=production rake assets:precompile"
end
